package org.github.overtane.soundbrowser

private const val PACKAGE_NAME = "org.github.overtane.soundbrowser"

const val SOUND_REQUEST_CODE = 0x42
const val SOUND_REQUEST_KEY = "$PACKAGE_NAME.SOUND_REQUEST"
const val SOUND_REPLY_KEY = "$PACKAGE_NAME.SOUND_REPLY"
const val SOUND_EXTRA_NAME = "$PACKAGE_NAME.NAME"
const val SOUND_EXTRA_URL = "$PACKAGE_NAME.URL"
const val SOUND_EXTRA_DURATION = "$PACKAGE_NAME.DURATION"
const val SOUND_EXTRA_CHANNELS = "$PACKAGE_NAME.CHANNELS"
const val SOUND_EXTRA_SAMPLE_RATE = "$PACKAGE_NAME.SAMPLE_RATE"
const val SOUND_EXTRA_PREVIEW = "$PACKAGE_NAME.PREVIEW"